"""@DeadlineRepository Protocol backing ./services.py, per ../architecture.sdd."""

from datetime import date
from typing import Protocol

from .domain import Deadline


class DeadlineRepository(Protocol):
    def get(self, deadline_id: int) -> Deadline | None: ...
    def list_for_realization(self, course_realization_id: int) -> list[Deadline]: ...
    def list_for_range(self, start: date, end: date) -> list[Deadline]: ...
    def add(self, course_realization_id: int, deadline_date: date, title: str) -> Deadline: ...
    def update(self, deadline_id: int, deadline_date: date, title: str) -> Deadline: ...
    def delete(self, deadline_id: int) -> None: ...