"""@HolidayRepository Protocol backing ./services.py, per ../architecture.sdd."""

from datetime import date
from typing import Protocol

from .domain import Holiday


class HolidayRepository(Protocol):
    def get(self, holiday_id: int) -> Holiday | None: ...
    def list_for_range(self, start: date, end: date) -> list[Holiday]: ...
    def add(self, holiday_date: date, title: str) -> Holiday: ...
    def update(self, holiday_id: int, holiday_date: date, title: str) -> Holiday: ...
    def delete(self, holiday_id: int) -> None: ...
