services:
  web:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      AIKANA_PASSWD: "${AIKANA_PASSWD:-}"
    volumes:
      - ./data:/data
