"""@NoTeachWeekRepository Protocol backing ./services.py, per ../architecture.sdd."""

from datetime import date
from typing import Protocol

from .domain import NoTeachWeek


class NoTeachWeekRepository(Protocol):
    def list_for_semester(self, semester_id: int) -> list[NoTeachWeek]: ...
    def get(self, no_teach_week_id: int) -> NoTeachWeek | None: ...
    def add(self, semester_id: int, week_number: int, week_start: date, title: str) -> NoTeachWeek: ...
    def update(self, no_teach_week_id: int, week_number: int, week_start: date, title: str) -> NoTeachWeek: ...
    def delete(self, no_teach_week_id: int) -> None: ...
