"""@CourseRealizationRepository Protocol backing ./services.py, per ../architecture.sdd."""

from typing import Protocol

from .domain import CourseRealization


class CourseRealizationRepository(Protocol):
    def list_for_course(self, course_id: int) -> list[CourseRealization]: ...
    def list_for_semester(self, semester_id: int) -> list[CourseRealization]: ...
    def get(self, realization_id: int) -> CourseRealization | None: ...
    def add(self, course_id: int, semester_id: int, group: str) -> CourseRealization: ...
    def update(
        self, realization_id: int, course_id: int, semester_id: int, group: str
    ) -> CourseRealization: ...
    def delete(self, realization_id: int) -> None: ...
