"""@ConferenceRepository Protocol backing ./services.py, per ../architecture.sdd."""

from datetime import date
from typing import Protocol

from .domain import Conference


class ConferenceRepository(Protocol):
    def get(self, conference_id: int) -> Conference | None: ...
    def list_for_range(self, start: date, end: date) -> list[Conference]: ...
    def add(self, conference_date: date, title: str) -> Conference: ...
    def update(self, conference_id: int, conference_date: date, title: str) -> Conference: ...
    def delete(self, conference_id: int) -> None: ...