"""@WeekThemeRepository Protocol backing ./services.py, per ../architecture.sdd."""

from datetime import date
from typing import Protocol

from .domain import WeekTheme


class WeekThemeRepository(Protocol):
    def list_for_realization(self, course_realization_id: int) -> list[WeekTheme]: ...
    def get(self, week_theme_id: int) -> WeekTheme | None: ...
    def add(self, course_realization_id: int, week_start: date, title: str) -> WeekTheme: ...
    def update(self, week_theme_id: int, week_start: date, title: str) -> WeekTheme: ...
    def delete(self, week_theme_id: int) -> None: ...